openapi: 3.0.0
info:
  title: Coin Market API
  version: 0.0.1
servers:
  - url: "http://localhost:5000"
    description: Local default dev server
paths:
  "/api/{symbol}/diff/{start}/{end}":
    parameters:
      - name: symbol
        in: path
        description: Coin symbol to find
        required: true
        schema:
          type: string
        examples:
          btc:
            value: BTC
            summary: Bitcoin's symbol
      - name: start
        in: path
        description: Date to start at
        required: true
        schema:
          type: string
          pattern: '^\d{4}-\d{2}-\d{2}$'
        examples:
          date:
            value: '2019-09-01'
            summary: start date
      - name: end
        in: path
        description: Date to end at
        required: true
        schema:
          type: string
          pattern: '^\d{4}-\d{2}-\d{2}$'
        examples:
          date:
            value: '2019-10-01'
            summary: end date
    get:
      description: Gets the daily closing info minus the previous day's numbers
      responses:
        200:
          description: Diff records
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/diff"
        404:
          description: Records not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"

  "/api/{symbol}/avg/{start}/{end}":
    parameters:
      - name: symbol
        in: path
        description: Coin symbol to find
        required: true
        schema:
          type: string
        examples:
          btc:
            value: BTC
            summary: Bitcoin's symbol
      - name: start
        in: path
        description: Date to start at
        required: true
        schema:
          type: string
          pattern: '^\d{4}-\d{2}-\d{2}$'
        examples:
          date:
            value: '2019-09-01'
            summary: start date
      - name: end
        in: path
        description: Date to end at
        required: true
        schema:
          type: string
          pattern: '^\d{4}-\d{2}-\d{2}$'
        examples:
          date:
            value: '2019-10-01'
            summary: end date
    get:
      description: Gets average high and low prices across the requested dates
      responses:
        200:
          description: Average hi/lo records
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/avg"
        404:
          description: Records not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"

  "/api/{symbol}/openings/{n}":
    parameters:
      - name: symbol
        in: path
        description: Coin symbol to find
        required: true
        schema:
          type: string
        examples:
          btc:
            value: BTC
            summary: Bitcoin's symbol
      - name: n
        in: path
        description: top openings to return
        required: true
        schema:
          type: integer
          minimum: 1
          maximum: 5
    get:
      description: Gets the top n openings available
      responses:
        200:
          description: Best openings ordered by price
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/openings"
        404:
          description: Records not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
components:
  schemas:
    error:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          description: What went wrong
    diff:
      type: object
      required:
        - diffs
        - symbol
        - start
        - end
      properties:
        diffs:
          type: array
          items:
            type: object
            properties:
              diffOpen:
                type: number
              diffHigh:
                type: number
              diffLow:
                type: number
              diffClose:
                type: number
              diffVolume:
                type: number
              diffTrades:
                type: number
              effectiveDate:
                type: string
                format: date
        symbol:
          type: string
        start:
          type: string
        end:
          type: string
    avg:
      type: object
      required:
        - averageHigh
        - averageLow
        - start
        - end
        - symbol
      properties:
        averageHigh:
          type: number
        averageLow:
          type: number
        symbol:
          type: string
        start:
          type: string
        end:
          type: string
    openings:
      type: object
      required:
        - best
      properties:
        best:
          type: array
          items:
            type: object
            properties:
              priceOpen:
                type: number
              priceHigh:
                type: number
              priceLow:
                type: number
              priceClose:
                type: number
              volumeTraded:
                type: number
              tradesCount:
                type: number
              effectiveDate:
                type: string
                format: date
